# Generated by Django 3.2.6 on 2021-08-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pokemon',
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_pokemons',
            field=models.ManyToManyField(blank=True, related_name='fav_pokemon', to='pokemon.Pokemon'),
        ),
    ]
